# 环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 8103
    servlet:
        # 应用的访问路径
        context-path: /
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30



# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://rm-bp1vy6r351sp8iz40.mysql.rds.aliyuncs.com:3306/rand_uat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: rand_uat
                password: Rand@789!
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: randing
                login-password: Rd98765!
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    # redis 配置
    redis:
        # 地址
        host: r-bp1o8ol73gy05u1svu.redis.rds.aliyuncs.com
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password: Uat9876!
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
# aliyun oss
aliyun:
    oss:
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
        keyid: LTAI5tK94yPS9uQ6VV7GQvLC
        keysecret: pXoj37ZxEqWEsoXpm57ZvXV8Qojetn
        bucketname: randing-dev-oss
        maxFileSize: 20  #MB
# 文件存储路径
file:
    mac:
        python: ~/data/randing-system/python/
        excelTemplate: ~/data/randing-system/excel/
        randomListExcelTemplate: ~/data/randing-system/downloadFile/随机列表模板.xlsx
        siteListExcelTemplate: ~/data/randing-system/downloadFile/研究中心导入模板.xlsx
        stockListExcelTemplate: ~/data/randing-system/downloadFile/仓库导入模板.xlsx
        prMemberListExcelTemplate: ·/data/randing-system/downloadFile/项目成员导入模板.xlsm
    linux:
        python: /data/randing-system/python/
        pythonApi: http://47.99.48.77:8090
        excelTemplate: /data/randing-system/excelTemplate/
        randomListExcelTemplate: /data/randing-system/downloadFile/随机列表模板.xlsx
        siteListExcelTemplate: /data/randing-system/downloadFile/研究中心导入模板.xlsx
        stockListExcelTemplate: /data/randing-system/downloadFile/仓库导入模板.xlsx
        prMemberListExcelTemplate: /data/randing-system/downloadFile/项目成员导入模板.xlsm
        stockdrugListExcelTemplate: /data/randing-system/downloadFile/包装清单导入模板.xlsx
    windows:
        python: D:\\
        pythonApi: http://localhost:8102
        excelTemplate: D:\\excelTemplate
        randomListExcelTemplate: C:\\Users\\patrickzh\\Desktop\\randing-b-system\\download\\随机列表模板.xlsx
        siteListExcelTemplate: C:\\Users\\leenm\\IdeaProjects\\randing-b-system\\download\\研究中心导入模板.xlsx
        stockListExcelTemplate: C:\\Users\\leenm\\IdeaProjects\\randing-b-system\\download\\仓库导入模板.xlsx
        prMemberListExcelTemplate: C:\\Users\\leenm\\IdeaProjects\\randing-b-system\\download\\项目成员导入模板.xlsx

#网页路径
webPage:
    domainName: https://www.ranwing.com/